# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('commodity_price', models.IntegerField(verbose_name='商品价格')),
                ('commodity_pub_date', models.DateField(verbose_name='发布日期')),
                ('commodity_image', models.ImageField(blank=True, upload_to='', verbose_name='商品图片')),
                ('commodity_introduce', models.TextField(verbose_name='商品介绍')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsClass', models.CharField(max_length=100, verbose_name='商品类别')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsComent', models.TextField(max_length=200, verbose_name='商品评价')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='commodity_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsClass', verbose_name='商品类别'),
        ),
    ]
