# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarouselName', models.CharField(max_length=100, verbose_name='Carousel名称')),
                ('CarouselImg', models.CharField(max_length=100, verbose_name='Carousel地址')),
            ],
        ),
    ]
