# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscarousel',
            name='CarouselIndex',
            field=models.CharField(blank=True, max_length=10, verbose_name='Carousel首图'),
        ),
    ]
