# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_goodscarousel_carouselindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsclass',
            name='GoogsClassImg',
            field=models.CharField(blank=True, max_length=200, verbose_name='商品类别图片'),
        ),
    ]
