# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodsclass_googsclassimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIndexShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsIndexShowName', models.CharField(max_length=100, verbose_name='首页展示商品名称')),
                ('GoodsIndexShowIntro', models.CharField(max_length=100, verbose_name='首页展示商品介绍')),
                ('GoodsIndexShowPrice', models.CharField(max_length=50, verbose_name='首页展示商品价格')),
            ],
        ),
    ]
