# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_goodsindexshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsindexshow',
            name='GoodsIndexShowImg',
            field=models.CharField(blank=True, max_length=100, verbose_name='首页展示商品图片'),
        ),
    ]
