# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goodsindexshow_goodsindexshowimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='commodity_image',
            field=models.CharField(blank=True, max_length=100, verbose_name='商品图片'),
        ),
    ]
