# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goodsPrice',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
