# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20170624_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goodsId',
            field=models.IntegerField(blank=True),
        ),
    ]
