# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='commodity_upload',
            field=models.ImageField(blank=True, null=True, upload_to='../'),
        ),
    ]
