# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_goods_commodity_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='commodity_upload',
            field=models.ImageField(blank=True, null=True, upload_to='goods'),
        ),
    ]
